# Generated by Django 5.2.7 on 2026-09-16 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_categoria_id_alter_movimiento_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario / Creado por'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='stock_anterior',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock anterior'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='stock_posterior',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock posterior'),
        ),
    ]
