# Generated by Django 5.2.7 on 2026-10-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='dni',
        ),
        migrations.AddField(
            model_name='cliente',
            name='domicilio',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Domicilio de entrega'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de documento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('DNI', 'DNI'), ('CUIT', 'CUIT')], max_length=10, null=True, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre / Razón social'),
        ),
    ]
