# Generated by Django 6.1.1 on 2026-10-06 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_ordencompra_movimiento_orden_compra_ordencompraitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='orden_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='inventario.ordencompra', verbose_name='Orden de compra'),
        ),
    ]
